OpenClash: bump to latest git HEAD
Co-authored-by: nameless3721 <50364156+nameless3721@users.noreply.github.com>
Co-authored-by: msylgj <msylgj@vip.qq.com>
Co-authored-by: Cubarco <marco.l.here@gmail.com>
Signed-off-by: Tianling Shen <cnsztl@immortalwrt.org>

diff --git a/applications/luci-app-openclash/root/etc/init.d/openclash b/applications/luci-app-openclash/root/etc/init.d/openclash
--- a/applications/luci-app-openclash/root/etc/init.d/openclash
+++ b/applications/luci-app-openclash/root/etc/init.d/openclash
@@ -981,15 +981,17 @@ do_run_file()
       exit 0
    fi
    
-   if ! capsh --is-uid=0 >/dev/null || ! capsh --has-ambient >/dev/null; then
-     echo "错误：Capsh异常，请尝试重新安装依赖【libcap】和相应的Capsh库，终止启动..." >$START_LOG
-     echo "${LOGTIME} Error: Could Not Load The Capsh Library, Please Verify The Capsh Shell Library Work Well" >> $LOG_FILE
-     echo "${LOGTIME} Tip: You Could Download And Re-Install The libcap & libcap-bin Library From The Address Below:" >> $LOG_FILE
-     echo "" >> $LOG_FILE
-     echo "---------- https://mirrors.cloud.tencent.com/lede/snapshots/packages/ ----------" >> $LOG_FILE
-     echo "" >> $LOG_FILE
-     sleep 5
-     start_fail
+   if [ -z "$_koolshare" ]; then
+      if ! capsh --is-uid=0 >/dev/null || ! capsh --has-ambient >/dev/null; then
+        echo "错误：Capsh异常，请尝试重新安装依赖【libcap】和相应的Capsh库，终止启动..." >$START_LOG
+        echo "${LOGTIME} Error: Could Not Load The Capsh Library, Please Verify The Capsh Shell Library Work Well" >> $LOG_FILE
+        echo "${LOGTIME} Tip: You Could Download And Re-Install The libcap & libcap-bin Library From The Address Below:" >> $LOG_FILE
+        echo "" >> $LOG_FILE
+        echo "---------- https://mirrors.cloud.tencent.com/lede/snapshots/packages/ ----------" >> $LOG_FILE
+        echo "" >> $LOG_FILE
+        sleep 5
+        start_fail
+      fi
    fi
    
    #创建原始备份
@@ -1025,16 +1027,20 @@ start_run_core()
    if [ -n "$(pidof clash)" ] && [ "$core_type" != "TUN" ] && [ "$config_reload" != "0" ]; then
       curl -s --connect-timeout 5 -m 5 -H 'Content-Type: application/json' -H "Authorization: Bearer ${da_password}" -XPUT http://"$lan_ip":"$cn_port"/configs -d "{\"path\": \"$CONFIG_FILE\"}" 2>/dev/null
    else
-      kill_clash
-      #防止赋权失败
-      touch /tmp/openclash.log 2>/dev/null
-      chmod o+w /etc/openclash/proxy_provider/* 2>/dev/null
-      chmod o+w /etc/openclash/rule_provider/* 2>/dev/null
-      chmod o+w /tmp/openclash.log 2>/dev/null
-      chown nobody:nogroup /etc/openclash/core/* 2>/dev/null
-      #使用nobody启动内核方便代理路由自身流量
-      capabilties="cap_sys_resource,cap_dac_override,cap_net_raw,cap_net_bind_service,cap_net_admin"
-      capsh --caps="${capabilties}+eip" -- -c "capsh --user=nobody --addamb='${capabilties}' -- -c 'nohup $CLASH -d $CLASH_CONFIG -f \"$CONFIG_FILE\" >> $LOG_FILE 2>&1 &'" >> $LOG_FILE 2>&1
+      if [ -z "$_koolshare" ]; then
+         kill_clash
+         #防止赋权失败
+         touch /tmp/openclash.log 2>/dev/null
+         chmod o+w /etc/openclash/proxy_provider/* 2>/dev/null
+         chmod o+w /etc/openclash/rule_provider/* 2>/dev/null
+         chmod o+w /tmp/openclash.log 2>/dev/null
+         chown nobody:nogroup /etc/openclash/core/* 2>/dev/null
+         #使用nobody启动内核方便代理路由自身流量
+         capabilties="cap_sys_resource,cap_dac_override,cap_net_raw,cap_net_bind_service,cap_net_admin"
+         capsh --caps="${capabilties}+eip" -- -c "capsh --user=nobody --addamb='${capabilties}' -- -c 'nohup $CLASH -d $CLASH_CONFIG -f \"$CONFIG_FILE\" >> $LOG_FILE 2>&1 &'" >> $LOG_FILE 2>&1
+      else
+         nohup $CLASH -d $CLASH_CONFIG -f "$CONFIG_FILE" >> $LOG_FILE 2>&1 &
+      fi
    fi
    uci -q set openclash.config.config_reload=1
    uci -q commit openclash
@@ -1232,11 +1238,25 @@ firewall_rule_exclude()
 firewall_redirect_exclude()
 {
    local section="$1"
-   local src_dport
+   local src_dport dest_port dest_ip proto enabled
    config_get "src_dport" "$section" "src_dport" ""
-   
-   if [ -z "$src_dport" ]; then
+   config_get "dest_port" "$section" "dest_port" ""
+   config_get "dest_ip" "$section" "dest_ip" ""
+   config_get "proto" "$section" "proto" ""
+   config_get "enabled" "$section" "enabled" ""
+
+   if [ -z "$src_dport" ] || [ a"$enabled" == a0 ]; then
       return
+   fi
+   local e_udp=false
+   local e_tcp=false
+   for p in $proto; do
+       if [ $p == tcp ]; then e_tcp=true; fi
+       if [ $p == udp ]; then e_udp=true; fi
+   done
+
+   if ! $e_udp && ! $e_tcp ; then
+       return
    fi
 
    if [ -z "$en_mode_tun" ] || [ "$en_mode_tun" -eq 3 ]; then
@@ -1248,6 +1268,12 @@ firewall_redirect_exclude()
    	  iptables -t mangle -I openclash_output -p udp --sport "$src_dport" -j RETURN >/dev/null 2>&1
       iptables -t mangle -I openclash -p tcp --dport "$src_dport" -j RETURN >/dev/null 2>&1
       iptables -t mangle -I openclash -p udp --dport "$src_dport" -j RETURN >/dev/null 2>&1
+      if $e_tcp ; then
+         iptables -t mangle -I openclash -p tcp -s "$dest_ip" --sport "$dest_port" -j RETURN >/dev/null 2>&1
+      fi
+      if $e_udp ; then
+         iptables -t mangle -I openclash -p udp -s "$dest_ip" --sport "$dest_port" -j RETURN >/dev/null 2>&1
+      fi
    fi
 
 }
@@ -1341,6 +1367,7 @@ fi
    ipset add localnetwork 224.0.0.0/4
    ipset add localnetwork 240.0.0.0/4
    ipset add localnetwork 172.16.0.0/12
+   ipset add localnetwork 100.64.0.0/10
 
    if [ -n "$wan_ip4" ]; then
       for wan_ip4s in $wan_ip4; do
@@ -1394,33 +1421,50 @@ if [ -z "$en_mode_tun" ] || [ "$en_mode_tun" -eq 3 ]; then
             iptables -t mangle -A openclash -m set ! --match-set common_ports dst -j RETURN >/dev/null 2>&1
             iptables -t mangle -A openclash -m set --match-set china_ip_route dst -j RETURN >/dev/null 2>&1
          fi
+      #quic
+         if [ "$disable_udp_quic" -eq 1 ]; then
+            iptables -I INPUT -p udp --dport 443 -j REJECT
+         fi
          iptables -t mangle -A openclash -p udp --dport 53 -j RETURN >/dev/null 2>&1
          iptables -t mangle -A openclash -p udp -j TPROXY --on-port "$proxy_port" --tproxy-mark "$PROXY_FWMARK"
          iptables -t mangle -A PREROUTING -p udp -j openclash
       fi
    fi
-
-   iptables -t nat -N openclash_output
-   iptables -t nat -F openclash_output
-   iptables -t nat -A openclash_output -m set --match-set localnetwork dst -j RETURN
-   if [ "$en_mode" = "fake-ip" ]; then
+   
+   if [ -z "$_koolshare" ]; then
+      iptables -t nat -N openclash_output
+      iptables -t nat -F openclash_output
+      iptables -t nat -A openclash_output -m set --match-set localnetwork dst -j RETURN
+      if [ "$en_mode" = "fake-ip" ]; then
+         if [ "$intranet_allowed" -eq 1 ]; then
+            iptables -t nat -A openclash_output -m owner ! --uid-owner 65534 -p tcp -d 198.18.0.0/16 -j DNAT --to-destination "$lan_ip:$proxy_port"
+         else
+            iptables -t nat -A openclash_output -m owner ! --uid-owner 65534 -p tcp -d 198.18.0.0/16 -j REDIRECT --to-ports "$proxy_port"
+         fi
+      fi
+      iptables -t nat -A openclash_output -m owner ! --uid-owner 65534 -m set ! --match-set common_ports dst -j RETURN >/dev/null 2>&1
+      if [ "$en_mode" = "redir-host" ]; then
+         iptables -t nat -A openclash_output -m set --match-set china_ip_route dst -j RETURN >/dev/null 2>&1
+      fi
       if [ "$intranet_allowed" -eq 1 ]; then
-         iptables -t nat -A openclash_output -m owner ! --uid-owner 65534 -p tcp -d 198.18.0.0/16 -j DNAT --to-destination "$lan_ip:$proxy_port"
+         iptables -t nat -A openclash_output -m owner ! --uid-owner 65534 -p tcp -j DNAT --to-destination "$lan_ip:$proxy_port"
       else
-         iptables -t nat -A openclash_output -m owner ! --uid-owner 65534 -p tcp -d 198.18.0.0/16 -j REDIRECT --to-ports "$proxy_port"
+         iptables -t nat -A openclash_output -m owner ! --uid-owner 65534 -p tcp -j REDIRECT --to-ports "$proxy_port"
+      fi
+      iptables -t nat -I OUTPUT -j openclash_output
+   else
+      if [ "$en_mode" = "fake-ip" ]; then
+         iptables -t nat -N openclash_output
+         iptables -t nat -F openclash_output
+         iptables -t nat -A openclash_output -m set --match-set localnetwork dst -j RETURN
+         if [ "$intranet_allowed" -eq 1 ]; then
+            iptables -t nat -A openclash_output -p tcp -d 198.18.0.0/16 -j DNAT --to-destination "$lan_ip:$proxy_port"
+         else
+            iptables -t nat -A openclash_output -p tcp -d 198.18.0.0/16 -j REDIRECT --to-ports "$proxy_port"
+         fi
+         
       fi
    fi
-   iptables -t nat -A openclash_output -m owner ! --uid-owner 65534 -m set ! --match-set common_ports dst -j RETURN >/dev/null 2>&1
-   if [ "$en_mode" = "redir-host" ]; then
-      iptables -t nat -A openclash_output -m set --match-set china_ip_route dst -j RETURN >/dev/null 2>&1
-   fi
-   if [ "$intranet_allowed" -eq 1 ]; then
-      iptables -t nat -A openclash_output -m owner ! --uid-owner 65534 -p tcp -j DNAT --to-destination "$lan_ip:$proxy_port"
-   else
-      iptables -t nat -A openclash_output -m owner ! --uid-owner 65534 -p tcp -j REDIRECT --to-ports "$proxy_port"
-   fi
-   iptables -t nat -I OUTPUT -j openclash_output
-
    #if [ "$ipv6_enable" -eq 1 ]; then
    #   #tcp
    #   ip6tables -t nat -N openclash
@@ -1471,14 +1515,18 @@ if [ -n "$en_mode_tun" ]; then
       iptables -t mangle -F openclash_output
       iptables -t mangle -A openclash_output -m set --match-set localnetwork dst -j RETURN
       if [ "$en_mode_tun" -ne 3 ]; then
-         iptables -t mangle -A openclash_output -m owner ! --uid-owner 65534 -d 198.18.0.0/16 -j MARK --set-mark "$PROXY_FWMARK"
-         iptables -t mangle -A openclash_output -m owner ! --uid-owner 65534 -m set ! --match-set common_ports dst -j RETURN >/dev/null 2>&1
-         iptables -t mangle -A openclash_output -m owner ! --uid-owner 65534 -p tcp -j MARK --set-mark "$PROXY_FWMARK"
-      else
+         if [ -z "$_koolshare" ]; then
+            iptables -t mangle -A openclash_output -m owner ! --uid-owner 65534 -d 198.18.0.0/16 -j MARK --set-mark "$PROXY_FWMARK"
+            iptables -t mangle -A openclash_output -m owner ! --uid-owner 65534 -m set ! --match-set common_ports dst -j RETURN >/dev/null 2>&1
+            iptables -t mangle -A openclash_output -m owner ! --uid-owner 65534 -p tcp -j MARK --set-mark "$PROXY_FWMARK"
+         else
+            iptables -t mangle -A openclash_output -d 198.18.0.0/16 -j MARK --set-mark "$PROXY_FWMARK"
+         fi
+      elif [ -z "$_koolshare" ]; then
          iptables -t mangle -A openclash_output -m owner ! --uid-owner 65534 -p udp -d 198.18.0.0/16 -j MARK --set-mark "$PROXY_FWMARK"
       fi
       iptables -t mangle -I OUTPUT -j openclash_output
-   elif [ "$en_mode" = "redir-host" ] && [ "$en_mode_tun" -ne 3 ]; then
+   elif [ -z "$_koolshare" ] && [ "$en_mode" = "redir-host" ] && [ "$en_mode_tun" -ne 3 ]; then
       iptables -t mangle -N openclash_output
       iptables -t mangle -F openclash_output
       iptables -t mangle -A openclash_output -m set --match-set localnetwork dst -j RETURN
@@ -1524,10 +1572,21 @@ if [ -n "$en_mode_tun" ]; then
    
    #snat routerself for tun while bindaddress enable
    if [ "$en_mode_tun" -ne 3 ] && [ "$intranet_allowed" -eq 1 ]; then
-      iptables -t nat -N openclash_post
-      iptables -t nat -F openclash_post
-      iptables -t nat -A openclash_post -m owner ! --uid-owner 65534 -i lo -d 127.0.0.1 -j SNAT --to-source "$lan_ip"
-      iptables -t nat -A POSTROUTING -j openclash_post
+      if [ -z "$_koolshare" ]; then
+         iptables -t nat -N openclash_post
+         iptables -t nat -F openclash_post
+         iptables -t nat -A openclash_post -m owner ! --uid-owner 65534 -i lo -d 127.0.0.1 -j SNAT --to-source "$lan_ip"
+         iptables -t nat -A POSTROUTING -j openclash_post
+      elif [ "$en_mode" = "fake-ip" ]; then
+         iptables -t nat -N openclash_post
+         iptables -t nat -F openclash_post
+         iptables -t nat -A openclash_post -i lo -d 127.0.0.1 -j SNAT --to-source "$lan_ip"
+         iptables -t nat -A POSTROUTING -j openclash_post
+      fi
+   fi
+   #quic
+   if [ "$disable_udp_quic" -eq 1 ]; then
+      iptables -I FORWARD -p udp --dport 443 -j REJECT 
    fi
 fi
 
@@ -1547,6 +1606,9 @@ revert_firewall()
    ip route del local 0.0.0.0/0 dev lo table "$PROXY_ROUTE_TABLE" >/dev/null 2>&1
 
    iptables -t nat -D PREROUTING -p tcp --dport 53 -j ACCEPT >/dev/null 2>&1
+   
+   iptables -D FORWARD -p udp --dport 443 -j REJECT >/dev/null 2>&1
+   iptables -D INPUT -p udp --dport 443 -j REJECT >/dev/null 2>&1
 
    out_lines=$(iptables -nvL OUTPUT -t nat |sed 1,2d |sed -n '/openclash/=' 2>/dev/null |sort -rn)
    for out_line in $out_lines; do
@@ -1650,6 +1712,7 @@ get_config()
    log_level=$(uci -q get openclash.config.log_level)
    intranet_allowed=$(uci -q get openclash.config.intranet_allowed)
    enable_udp_proxy=$(uci -q get openclash.config.enable_udp_proxy)
+   disable_udp_quic=$(uci -q get openclash.config.disable_udp_quic)
    operation_mode=$(uci -q get openclash.config.operation_mode)
    lan_ac_mode=$(uci -q get openclash.config.lan_ac_mode)
    enable_rule_proxy=$(uci -q get openclash.config.enable_rule_proxy)
@@ -1660,6 +1723,7 @@ get_config()
    interface_name=$(uci -q get openclash.config.interface_name)
    common_ports=$(uci -q get openclash.config.common_ports)
    dns_port=$(uci -q get openclash.config.dns_port)
+   _koolshare=$(cat /usr/lib/os-release 2>/dev/null |grep OPENWRT_RELEASE 2>/dev/null |grep -i koolshare 2>/dev/null)
    [ -z "$dns_port" ] && dns_port=7874 && uci -q set openclash.config.dns_port=7874
    uci -q set openclash.config.restricted_mode=0 && uci -q commit openclash
 }
